package main.util;

public enum Endpoint {
    GET_TASKS,
    GET_TASK_BY_ID,
    POST_TASK,
    DELETE_TASK,
    DELETE_ALL_TASK,
    GET_SUBTASKS,
    GET_SUBTASK_BY_ID,
    POST_SUBTASK,
    DELETE_SUBTASK,
    DELETE_ALL_SUBTASK,
    GET_EPICS,
    GET_EPIC_BY_ID,
    GET_EPIC_SUBTASKS,
    POST_EPIC,
    DELETE_EPIC,
    DELETE_ALL_EPIC,
    GET_HISTORY,
    GET_PRIORITIZED,
    UNKNOWN
}
